/*
 * This source file was generated by the Gradle 'init' task
 */
package org.wharvex.jflap;

import org.wharvex.jflap.gui.GUIMain;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    System.out.println(System.getProperty("user.dir"));
    GUIMain.main(args, true);
  }

  public static String getBasePackageDir() {
    return System.getProperty("user.dir") +
        "/src/main/java/org/wharvex/jflap/";
  }
}
